on: [push]
jobs:
  test:
    runs-on: windows-latest
    name: Build Executable
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile .exe
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install pyinstaller
        run: pip install pyinstaller
      - name: Compile .exe
        run: ./build.ps1