on: [push]
jobs:
  #
  # Run rage-lint tests
  #
  test:
    runs-on: ubuntu-latest
    name: Run XSD Linting Tests
    container:
      image: python:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python ./tests/run_tests.py
  #
  # Build Windows executable
  #
  build-win:
    runs-on: windows-latest
    name: Build Executable (Windows)
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Compile rage-lint.exe
        run: ./.build/build.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: rage-lint.exe
          path: .build/dist/rage-lint.exe
          retention-days: 90