on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run XSD Linting Tests
    container:
      image: python:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Lint tests
        uses: docker://python:latest
        with:
          args: |
            /bin/sh -c " \
            pip install -r requirements.txt
            python ./tests/run_tests.py